/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StackRouteImport } from './routes/stack'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as HireRouteImport } from './routes/hire'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CertificationsRouteImport } from './routes/certifications'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminCertsRouteImport } from './routes/admin.certs'

const StackRoute = StackRouteImport.update({
  id: '/stack',
  path: '/stack',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const HireRoute = HireRouteImport.update({
  id: '/hire',
  path: '/hire',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationsRoute = CertificationsRouteImport.update({
  id: '/certifications',
  path: '/certifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCertsRoute = AdminCertsRouteImport.update({
  id: '/certs',
  path: '/certs',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/certifications': typeof CertificationsRoute
  '/contact': typeof ContactRoute
  '/hire': typeof HireRoute
  '/projects': typeof ProjectsRoute
  '/resume': typeof ResumeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stack': typeof StackRoute
  '/admin/certs': typeof AdminCertsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/certifications': typeof CertificationsRoute
  '/contact': typeof ContactRoute
  '/hire': typeof HireRoute
  '/projects': typeof ProjectsRoute
  '/resume': typeof ResumeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stack': typeof StackRoute
  '/admin/certs': typeof AdminCertsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/certifications': typeof CertificationsRoute
  '/contact': typeof ContactRoute
  '/hire': typeof HireRoute
  '/projects': typeof ProjectsRoute
  '/resume': typeof ResumeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stack': typeof StackRoute
  '/admin/certs': typeof AdminCertsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/certifications'
    | '/contact'
    | '/hire'
    | '/projects'
    | '/resume'
    | '/sitemap.xml'
    | '/stack'
    | '/admin/certs'
    | '/admin/messages'
    | '/admin/projects'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/certifications'
    | '/contact'
    | '/hire'
    | '/projects'
    | '/resume'
    | '/sitemap.xml'
    | '/stack'
    | '/admin/certs'
    | '/admin/messages'
    | '/admin/projects'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/certifications'
    | '/contact'
    | '/hire'
    | '/projects'
    | '/resume'
    | '/sitemap.xml'
    | '/stack'
    | '/admin/certs'
    | '/admin/messages'
    | '/admin/projects'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CertificationsRoute: typeof CertificationsRoute
  ContactRoute: typeof ContactRoute
  HireRoute: typeof HireRoute
  ProjectsRoute: typeof ProjectsRoute
  ResumeRoute: typeof ResumeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StackRoute: typeof StackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stack': {
      id: '/stack'
      path: '/stack'
      fullPath: '/stack'
      preLoaderRoute: typeof StackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire': {
      id: '/hire'
      path: '/hire'
      fullPath: '/hire'
      preLoaderRoute: typeof HireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certifications': {
      id: '/certifications'
      path: '/certifications'
      fullPath: '/certifications'
      preLoaderRoute: typeof CertificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/certs': {
      id: '/admin/certs'
      path: '/certs'
      fullPath: '/admin/certs'
      preLoaderRoute: typeof AdminCertsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCertsRoute: typeof AdminCertsRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCertsRoute: AdminCertsRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CertificationsRoute: CertificationsRoute,
  ContactRoute: ContactRoute,
  HireRoute: HireRoute,
  ProjectsRoute: ProjectsRoute,
  ResumeRoute: ResumeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StackRoute: StackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
